### PR TITLE
add event to VisitsFake execution so plugins can add fake data specific to the plugin if desired

### PR DESCRIPTION
**Pull request by diosmosis**
### Description:

Example usage:

```
    public function registerEvents()
    {
        return [
            'VisitorGenerator.VisitsFake.trackVisit' => 'trackFakeStuff',
        ];
    }

    public function trackFakeStuff(\MatomoTracker $t, \Faker\Generator $faker)
    {
        if (!$faker->boolean(30)) {
            return;
        }

        $t->clearCustomTrackingParameters();

        $stuff = $faker->randomElement(FakeStuff::$stuffs);
        $stuffType = $faker->randomElement(FakeStuff::$types);

        $stuffOrigin = null;
        if ($faker->boolean(80)) {
            $stuffOrigin = $faker->randomElement(FakeStuff::$origins);
        }

        $category = null;
        if ($faker->boolean(33)) {
            $category = $faker->randomElement(FakeStuff::$categories);
        }

        $params = [
            'ca' => '1',
            RequestProcessor::TRACKING_PARAM_STUFF => $stuff,
            RequestProcessor::TRACKING_PARAM_STUFF_TYPE => $stuffType,
            RequestProcessor::TRACKING_PARAM_STUFF_ORIGIN => $stuffOrigin,
            RequestProcessor::TRACKING_PARAM_STUFF_CATEGORY => $category,
        ];
        foreach ($params as $name => $value) {
            if ($value) {
                $t->setCustomTrackingParameter($name, $value);
            }
        }

        $t->storedTrackingActions[] = $t->getUrlTrackPageView('This does not appear as page view');
        $t->clearCustomTrackingParameters();
    }
```

### Review

* [ ] [Functional review done](https://developer.matomo.org/guides/pull-request-reviews#functional-review-done)
* [ ] [Potential edge cases thought about](https://developer.matomo.org/guides/pull-request-reviews#potential-edge-cases-thought-about) (behavior of the code with strange input, with strange internal state or possible interactions with other Matomo subsystems)
* [ ] [Usability review done](https://developer.matomo.org/guides/pull-request-reviews#usability-review-done) (is anything maybe unclear or think about anything that would cause people to reach out to support)
* [ ] [Security review done](https://developer.matomo.org/guides/security-in-piwik#checklist)
* [ ] [Wording review done](https://developer.matomo.org/guides/pull-request-reviews#translations-wording-review-done)
* [ ] [Code review done](https://developer.matomo.org/guides/pull-request-reviews#code-review-done)
* [ ] [Tests were added if useful/possible](https://developer.matomo.org/guides/pull-request-reviews#tests-were-added-if-usefulpossible)
* [ ] [Reviewed for breaking changes](https://developer.matomo.org/guides/pull-request-reviews#reviewed-for-breaking-changes)
* [ ] [Developer changelog updated if needed](https://developer.matomo.org/guides/pull-request-reviews#developer-changelog-updated-if-needed)
* [ ] [Documentation added if needed](https://developer.matomo.org/guides/pull-request-reviews#documentation-added-if-needed)
* [ ] Existing documentation updated if needed

### CODE REVIEW

**Review by snake14 — APPROVED** [review]
@diosmosis I haven't had a chance to test it out, but it's just adding a new event, so I think it looks good. Any concerns @sgiehl ?

**Comment by sgiehl** [comment]
No concerns from me. We could though maybe add the usage example into the code description. Maybe this might be of help for other developers not knowing what the event is thought for.

**Comment by diosmosis** [comment]
@snake14 @sgiehl updated

**Comment by snake14** [comment]
@diosmosis Looks good to me :+1:

**Comment by tsteur** [comment]
FYI I'll merge this as everyone gave their thumbs up. I need the change to test something.

**Pull request merged**
